---
title: "Project Analysis Report"
author: "Authors: Connie, Laura, Rachel, Ekta, Tiana"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Background** 
The rate of drug related deaths in Connecticut is currently higher than the national average and has continued to steadily increase. While there have been a sigficicant number of initiatives implemented to reduce drug misuse in recent years, it is important to understand the demographic and geogrphaic attributes underlying this public health issue in order to effectively reduce drug-related deaths in vulnerable populations. 

## **Initial Questions**
* What are demographic characteristics of individuals who experienced a drug-related death in Connecticut? 
* Where are these deaths mainly occurring within the state? 
* Are there seasonal variations in deaths across each year? 
* What specific drug types have been attributed to the increase in drug-related deaths? 

## **Data** 
In order to address our initial research questions, we were interested in specific variables within the [Accidental Drug Related Deaths](https://catalog.data.gov/dataset/accidental-drug-related-deaths-january-2012-sept-2015) dataset after tidying and cleaning. Variables used included attributes and characterstics of individuals at time of death, details of location of death, and type of drug used prior to death.

*Below is a list of variables used in alphabetical order:*

`age`: Age of individual at death

`death_city_long` and `death_city_lat`: Location of death by longitude and latitude

`drug`: Type of drug which include heroin, fentanyl, cocaine, eethanol, benzodiazepine, and other 

`location`: Location of death categorized by location type including nursing home, hsopice, or convalescent home and residence, and hospital, and other. 

`month` and `year`: Details of date of death

`race`: Race of individual which include White, Black, Hispanic White, Asian, Hispanic Black, and other

`sex`: Sex of individual which include male, female, or unknown 




## **Exploratory Analysis and Findings** 
### Temporal analysis of death from 2015-2018

* 

### Distribution of death by race, gender, age

* 

### Death count attributed to each drug type 

* 

### Location of death across Connecticut

* 




## **Discussion**
* Suggestions for modes of intervention, how findings could impact understanding of drug-overdose deaths
* Limitations included: not knowing what 'other' drugs included which could impact analysis 