---
title: "Project Proposal" 
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Group Members 
* Connie Zhang (cz2540)
* Laura Lynch (ll3255)
* Rachel Crowley (rac2224)
* Ekta Chaudhary (ec3342)

## Project Title (tentative)
Assessment of Drug Use and Treatment in State of Massachusetts 

## Motivation for project 
The opioid crisis is an ongoing public health issue on a national level, and in the state of Massachusetts in particular. From our own research we have seen that there has been a dramatic increase in opioid related deaths in this state that is well above the national average. 

Source: https://chapter55.digital.mass.gov/

## Intended final products 
Analysis page, final report page, screen cast, and some sort of interactive visualization page. 

## Anticipated Data Sources 
Mass.gov PHIT (Population Health Information Tool) catalog. This is a data portal for Massachusetts health data that allows researchers to explore issues, analyze specific communities, and compare health measures. Potential data topics we intend to include alongside the substance abuse and treatment data include: social determinants of health and environmental health. 

Source: https://www.mass.gov/guides/population-health-information-tool-phit-data-directory

## Planned analyses, visualizaitons, coding challenges
This project will look at hospitalization and substance abuse treatment demographics over time in the state of Massachusetts. For example, differences in gender, race, and age will be assessed. Visualizations may includes maps of outcomes in specific communities (i.e. rates of hopsitalization, density of drug treatment services). 

Anticipated coding challenges could include making external generalizations nad assumptions from our analyses to the broader state of Massachusetts, since this dataset may only capture a very specific population of individuals who are hospitalized and seeking treatment. While coding, it will be important to also clean the data, keeping in mind individuals who are hospitalized may not be the same as individuals seeking treatment. Therefore, trends in the data must be analyzed with this this caveat.

## Timeline 
Week 0 (Nov 11 - 15):

* Proposal approved after review meeting
* Data tidied

Week 1 (Nov 18 - 22):

* Initial data exploration/visualization
* Final data visualizations/conclusions

Week 2 (Nov 25 - Dec 29):

* Create final report, website and screencast

Week 3 (Dec 1 - Dec 4): 

* Finish up deliverables
